substitutions:
  device_id: treatlife_ss02

esphome:
  name: treatlife-3-way

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "mO3JCb5B/n48zyo/Yf32L7YWrHwteGujmOF/IfyB9Ro="

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Treatlife-3-Way Fallback Hotspot"
    password: "nvm6Lm1P8B9j"

captive_portal:    
    
binary_sensor:
  - platform: gpio
    id: power_sensor
    pin:
      number: GPIO14
      inverted: True
    filters:
      - delayed_off: 50ms
    on_press:
      - light.turn_on: white_led
      - light.turn_off: red_led
    on_release:
      - light.turn_off: white_led
      - light.turn_on: red_led
    internal: True

  - platform: gpio
    pin:
      number: GPIO13
      inverted: True
    id: button
    internal: True
    on_multi_click:
    # Single Click:
    - timing:
      - ON for at most 1s
      - OFF for at least 0.3s
      then:
        - switch.toggle: ${device_id}
        - logger.log: "Single Click"
        - homeassistant.event:
            event: esphome.${device_id}
            data:
              title: single_click
    # Double Click:
    - timing:
      - ON for at most 1s
      - OFF for at most 1s
      - ON for at most 1s
      - OFF for at least 0.2s
      then:
        - logger.log: "Double Clicked"
        - homeassistant.event:
            event: esphome.${device_id}
            data:
              title: double_click
    # Long Press:
    - timing:
      - ON for 1s to 2s
      - OFF for at least 0.3s
      then:
        - logger.log: "Single Long Press"
        - homeassistant.event:
            event: esphome.${device_id}
            data:
              title: long_press
    - timing:
      - ON for at least 2.2s
      then:
        - logger.log: "Press and Hold"
        - homeassistant.event:
            event: esphome.${device_id}
            data:
              title: hold

light:
  - platform: binary
    id: white_led
    name: "White LED"
    output: led_1
    internal: True
  
  - platform: status_led  
    id: red_led   
    name: "Red LED" 
    pin:
      number: GPIO5
      inverted: True
    internal: True

output:
  - platform: gpio
    id: led_1
    pin:
      number: GPIO4
            
switch:
  - platform: gpio
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF
    internal: True

  - platform: template
    name: "Treatlife 3-way"
    id: ${device_id}
    lambda: |-
      if (id(power_sensor).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
    - if:
        condition:
          - binary_sensor.is_off: power_sensor
        then:
          - switch.toggle: relay
    turn_off_action:
    - if:
        condition:
          - binary_sensor.is_on: power_sensor
        then:
          - switch.toggle: relay