esphome:
  name: wemos-d1

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "9Grf3HEVYLKcAfixgrog9K9ZtAtiX2fzqU3E5/XAyhg="

ota:
  password: "93db6e87f92d30ff77a283384db54721"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wemos-D1 Fallback Hotspot"
    password: "iGDCgowu4m9k"

captive_portal:

switch:
  - platform: "gpio"
    id: "close_value" 
    pin: D5
    name: "D5-GPIO14 Close"
    
  - platform: "gpio"
    id: "open_value"
    pin: D6
    name: "D6-GPIO12 Open"
        
output:
  - platform: gpio
    id: "led"
    pin: D4
    inverted: True

light:  
  - name: "D4-GPIO2 10k pull-up LED" 
    platform: binary
    output: led

binary_sensor:
  - platform: gpio
    pin: D0
    name: "D0-GPIO16"

  - platform: gpio
    pin: D1
    name: "D1-GPIO5"
    
  - platform: gpio
    pin: D2
    name: "D2-GPIO4"
    
  - platform: gpio
    pin: D3
    name: "D3-GPIO0 10k pull-up"
    
  - platform: gpio
    pin: D7
    name: "D7-GPIO13"
    
  - platform: gpio
    pin: D8
    name: "D8-GIPO15 10k pull-down"
    
sensor:
  - platform: adc
    pin: A0
    name: "A0-Analog 3.3V max"
    device_class: pressure        

web_server:
  port: 80
  
  